# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Author, Li Jun, Zhu <zhuljbj@cn.ibm.com>

- hosts: localhost
  vars:
    modules_path:
    checkout_dir: 'ibmi_repo'

  tasks:
    - name: Find the ansible modules path
      command: ansible --version
      register: ansible_output     
    
    - set_fact: "modules_path={{((item.split('='))[-1]).replace(' ','')}}"
      when: item is search("ansible python module location")
      with_list: "{{ansible_output.stdout_lines}}"

    - name: Move ibmi module to modules path
      copy:
        src: '../../../../lib/ansible/'
        dest: '{{modules_path}}'
        force: no
        mode: 0644