---
# Install PTFs from image catalog
- hosts: ibmi
  vars:
    #Required parameters
    fix_repo_directory: "/home/wangyun"
    fix_name: "S2018V01.BIN"
    fix_install_path: "/home/ansiblePTFInstallTemp/"
    product_id: '5733SC1'
    lib_name: 'ANSIIBMI'
    savf_name: 'ANSISAVF'
    
  tasks:
    - block:
      - name: Create symlink for python
        file:
          state: link
          src: /QOpensys/pkgs/bin/python2
          path: /usr/bin/python
        ignore_errors: true

      - debug: 
          msg: '{{ansible_facts}}'

      - name: assert facts
        assert:
          that:
            - "'{{ansible_system}}' == 'OS400'"

      - name: Create library
        ibmi_cl_command:
          cmd: CRTLIB LIB({{lib_name}})
        ignore_errors: true

      - name: Create savf
        ibmi_cl_command:
          cmd: CRTSAVF FILE({{lib_name}}/{{savf_name}})

      - name: find the created object
        ibmi_object_find: 
          lib_name: "{{lib_name}}"
          object_name: "{{savf_name}}"
        register: find_result

      - name: assert 1 object was found
        assert:
          that:
            - find_result.object_list | length == 1

      - name: Show found object returned by ibmi_object_find module.
        debug: var=find_result verbosity=0

      - name: Reboot the IBM i system by ibmi_reboot module
        ibmi_reboot:
          how_to_end: '*IMMED'